CREATE TABLE IF NOT EXISTS STOCK_DATA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stock VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    oi_interpretation VARCHAR(255)
);